package com.hgs.patient.siags_backend.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Entity
@Table(name = "patients") // Table name can remain 'patients' or be renamed to 'patients' (already English)
@Data // Lombok automatically generates getters, setters, toString, equals and hashCode
@NoArgsConstructor // Added for a default constructor required by JPA
@AllArgsConstructor // Useful for easily creating Patient objects
public class Patient {

    @Id // Indicates that this field is the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique patient identifier

    @Column(nullable = false, length = 100)
    @NotBlank(message = "Le nom est obligatoire")
    @Size(max = 100, message = "Le nom ne doit pas dépasser 100 caractères")
    private String lastName; // Renamed from 'nom'

    @Column(nullable = false, length = 100)
    @NotBlank(message = "Le prénom est obligatoire")
    @Size(max = 100, message = "Le prénom ne doit pas dépasser 100 caractères")
    private String firstName;

    @Column(length = 10) // Max length 10 characters for gender (e.g., "MASCULIN", "FEMININ")
    @Size(max = 10, message = "Le genre ne doit pas dépasser 10 caractères")
    private String gender;

    @Column(name = "birth_date") // Column name in DB 'birth_date'
    @PastOrPresent(message = "La date de naissance ne peut pas être dans le futur") // Changed @Past to @PastOrPresent
    private LocalDate birthDate;

    @Column(length = 150)
    @Size(max = 150, message = "L'adresse ne doit pas dépasser 150 caractères")
    private String address;

    @Column(name = "phone_number", length = 20) // Column name in DB 'phone_number'
    @Size(max = 20, message = "Le téléphone ne doit pas dépasser 20 caractères")
    private String phoneNumber;

    @Column(name = "record_number", unique = true, length = 50) // Must be unique in the database
    @NotBlank(message = "Le numéro de dossier est obligatoire")
    @Size(max = 50, message = "Le numéro de dossier ne doit pas dépasser 50 caractères")
    private String recordNumber; // Renamed from 'numeroDossier' - Unique record number generated by the Admission Agent

    // Missing fields added (original names were already English, but adjusted column names for consistency):
    @Column(length = 100)
    @Email(message = "L'email doit être valide")
    @Size(max = 100, message = "L'email ne doit pas dépasser 100 caractères")
    private String email;

    @Column(name = "blood_type", length = 5) // Column name in DB 'blood_type'
    @Size(max = 5, message = "Le type de sang ne doit pas dépasser 5 caractères")
    private String bloodType; // Renamed from 'typeDeSang'

    @Column(name = "known_illnesses", columnDefinition = "TEXT") // Column name in DB 'known_illnesses'
    private String knownIllnesses; // Renamed from 'maladiesConnues'

    @Column(columnDefinition = "TEXT")
    private String allergies; // Renamed from 'allergies' (name was already English)

}